export const ADD_TO_DOS = "ADD_TO_DO"
export const DELETE_TO_DOS = "DELETE_TO_DO"
export const MARK_TO_DOS = "MARK_TO_DOS"
export const DELETE_ALL_TO_DOS = "DELETE_ALL_TO_DOS"
export const SAVE_NAME = "SAVE_NAME"